update public.players
set active = false
where team_name in ('Colombia', 'Uzbekistan', 'R. D. del Congo', 'Portugal');

insert into public.players (team_name, name, position, display_order, active)
values
  ('Colombia', 'David Ospina', 'Arquero', 1, true),
  ('Colombia', 'Camilo Vargas', 'Arquero', 2, true),
  ('Colombia', 'Alvaro Montero', 'Arquero', 3, true),
  ('Colombia', 'Daniel Munoz', 'Defensa', 20, true),
  ('Colombia', 'Jhon Lucumi', 'Defensa', 21, true),
  ('Colombia', 'Santiago Arias', 'Defensa', 22, true),
  ('Colombia', 'Yerry Mina', 'Defensa', 23, true),
  ('Colombia', 'Gustavo Puerta', 'Defensa', 24, true),
  ('Colombia', 'Johan Mojica', 'Defensa', 25, true),
  ('Colombia', 'Willer Ditta', 'Defensa', 26, true),
  ('Colombia', 'Deiver Machado', 'Defensa', 27, true),
  ('Colombia', 'Davinson Sanchez', 'Defensa', 28, true),
  ('Colombia', 'Kevin Castano', 'Mediocampista', 40, true),
  ('Colombia', 'Richard Rios', 'Mediocampista', 41, true),
  ('Colombia', 'Jorge Carrascal', 'Mediocampista', 42, true),
  ('Colombia', 'James Rodriguez', 'Mediocampista', 43, true),
  ('Colombia', 'Jhon Arias', 'Mediocampista', 44, true),
  ('Colombia', 'Juan Portilla', 'Mediocampista', 45, true),
  ('Colombia', 'Jefferson Lerma', 'Mediocampista', 46, true),
  ('Colombia', 'Juan Quintero', 'Mediocampista', 47, true),
  ('Colombia', 'Luis Diaz', 'Delantero', 60, true),
  ('Colombia', 'Jhon Cordoba', 'Delantero', 61, true),
  ('Colombia', 'Cucho Hernandez', 'Delantero', 62, true),
  ('Colombia', 'Jaminton Campaz', 'Delantero', 63, true),
  ('Colombia', 'Luis Suarez', 'Delantero', 64, true),
  ('Colombia', 'Andres Gomez', 'Delantero', 65, true),
  ('Uzbekistan', 'Utkir Yusupov', 'Arquero', 1, true),
  ('Uzbekistan', 'Abduvohid Nematov', 'Arquero', 2, true),
  ('Uzbekistan', 'Botirali Ergashev', 'Arquero', 3, true),
  ('Uzbekistan', 'Abdukodir Khusanov', 'Defensa', 20, true),
  ('Uzbekistan', 'Khojiakbar Alijonov', 'Defensa', 21, true),
  ('Uzbekistan', 'Farrukh Sayfiev', 'Defensa', 22, true),
  ('Uzbekistan', 'Rustam Ashurmatov', 'Defensa', 23, true),
  ('Uzbekistan', 'Sherzod Nasrullaev', 'Defensa', 24, true),
  ('Uzbekistan', 'Umar Eshmurodov', 'Defensa', 25, true),
  ('Uzbekistan', 'Abdulla Abdullaev', 'Defensa', 26, true),
  ('Uzbekistan', 'Behruzjon Karimov', 'Defensa', 27, true),
  ('Uzbekistan', 'Avazbek Ulmasaliyev', 'Defensa', 28, true),
  ('Uzbekistan', 'Jakhongir Urozov', 'Defensa', 29, true),
  ('Uzbekistan', 'Akmal Mozgovoy', 'Mediocampista', 40, true),
  ('Uzbekistan', 'Otabek Shukurov', 'Mediocampista', 41, true),
  ('Uzbekistan', 'Jamshid Iskanderov', 'Mediocampista', 42, true),
  ('Uzbekistan', 'Odiljon Xamrobekov', 'Mediocampista', 43, true),
  ('Uzbekistan', 'Ruslanbek Jiyanov', 'Mediocampista', 44, true),
  ('Uzbekistan', 'Oston Urunov', 'Mediocampista', 45, true),
  ('Uzbekistan', 'Dostonbek Khamdamov', 'Mediocampista', 46, true),
  ('Uzbekistan', 'Azizjon Ganiev', 'Mediocampista', 47, true),
  ('Uzbekistan', 'Abbosbek Fayzullaev', 'Mediocampista', 48, true),
  ('Uzbekistan', 'Sherzod Esanov', 'Mediocampista', 49, true),
  ('Uzbekistan', 'Eldor Shomurodov', 'Delantero', 60, true),
  ('Uzbekistan', 'Azizbek Amonov', 'Delantero', 61, true),
  ('Uzbekistan', 'Igor Sergeev', 'Delantero', 62, true),
  ('R. D. del Congo', 'Lionel Mpasi', 'Arquero', 1, true),
  ('R. D. del Congo', 'Timothy Fayulu', 'Arquero', 2, true),
  ('R. D. del Congo', 'Matthieu Epolo', 'Arquero', 3, true),
  ('R. D. del Congo', 'Aaron Wan-Bissaka', 'Defensa', 20, true),
  ('R. D. del Congo', 'Steve Kapuadi', 'Defensa', 21, true),
  ('R. D. del Congo', 'Axel Tuanzebe', 'Defensa', 22, true),
  ('R. D. del Congo', 'Dylan Batubinsika', 'Defensa', 23, true),
  ('R. D. del Congo', 'Joris Kayembe', 'Defensa', 24, true),
  ('R. D. del Congo', 'Chancel Mbemba', 'Defensa', 25, true),
  ('R. D. del Congo', 'Gedeon Kalulu', 'Defensa', 26, true),
  ('R. D. del Congo', 'Arthur Masuaku', 'Defensa', 27, true),
  ('R. D. del Congo', 'Ngalayel Mukau', 'Mediocampista', 40, true),
  ('R. D. del Congo', 'Nathanael Mbuku', 'Mediocampista', 41, true),
  ('R. D. del Congo', 'Samuel Moutoussamy', 'Mediocampista', 42, true),
  ('R. D. del Congo', 'Theo Bongonda', 'Mediocampista', 43, true),
  ('R. D. del Congo', 'Noah Sadiki', 'Mediocampista', 44, true),
  ('R. D. del Congo', 'Aaron Tshibola', 'Mediocampista', 45, true),
  ('R. D. del Congo', 'Charles Pickel', 'Mediocampista', 46, true),
  ('R. D. del Congo', 'Edo Kayembe', 'Mediocampista', 47, true),
  ('R. D. del Congo', 'Brian Cipenga', 'Delantero', 60, true),
  ('R. D. del Congo', 'Gael Kakuta', 'Delantero', 61, true),
  ('R. D. del Congo', 'Meschack Elia', 'Delantero', 62, true),
  ('R. D. del Congo', 'Cedric Bakambu', 'Delantero', 63, true),
  ('R. D. del Congo', 'Fiston Mayele', 'Delantero', 64, true),
  ('R. D. del Congo', 'Yoane Wissa', 'Delantero', 65, true),
  ('R. D. del Congo', 'Simon Banza', 'Delantero', 66, true),
  ('Portugal', 'Diogo Costa', 'Arquero', 1, true),
  ('Portugal', 'Jose Sa', 'Arquero', 2, true),
  ('Portugal', 'Rui Silva', 'Arquero', 3, true),
  ('Portugal', 'Nelson Semedo', 'Defensa', 20, true),
  ('Portugal', 'Ruben Dias', 'Defensa', 21, true),
  ('Portugal', 'Tomas Araujo', 'Defensa', 22, true),
  ('Portugal', 'Diogo Dalot', 'Defensa', 23, true),
  ('Portugal', 'Renato Veiga', 'Defensa', 24, true),
  ('Portugal', 'Goncalo Inacio', 'Defensa', 25, true),
  ('Portugal', 'Joao Cancelo', 'Defensa', 26, true),
  ('Portugal', 'Samu Costa', 'Defensa', 27, true),
  ('Portugal', 'Nuno Mendes', 'Defensa', 28, true),
  ('Portugal', 'Matheus Nunes', 'Mediocampista', 40, true),
  ('Portugal', 'Bruno Fernandes', 'Mediocampista', 41, true),
  ('Portugal', 'Bernardo Silva', 'Mediocampista', 42, true),
  ('Portugal', 'Joao Neves', 'Mediocampista', 43, true),
  ('Portugal', 'Ruben Neves', 'Mediocampista', 44, true),
  ('Portugal', 'Vitinha', 'Mediocampista', 45, true),
  ('Portugal', 'Cristiano Ronaldo', 'Delantero', 60, true),
  ('Portugal', 'Goncalo Ramos', 'Delantero', 61, true),
  ('Portugal', 'Joao Felix', 'Delantero', 62, true),
  ('Portugal', 'Francisco Trincao', 'Delantero', 63, true),
  ('Portugal', 'Rafael Leao', 'Delantero', 64, true),
  ('Portugal', 'Pedro Neto', 'Delantero', 65, true),
  ('Portugal', 'Goncalo Guedes', 'Delantero', 66, true),
  ('Portugal', 'Francisco Conceicao', 'Delantero', 67, true)
on conflict (team_name, name)
do update set
  position = excluded.position,
  display_order = excluded.display_order,
  active = true;
